name: rag_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.0
  - scikit-learn=1.3.0
  - pip:
      - torch>=2.0.0
      - transformers==4.40.0
      - sentence-transformers==2.2.2
      - faiss-cpu==1.7.4
      - flask==2.2.5
      - uvicorn==0.23.0
